### ISSUE TITLE
iOS use

### ISSUE THREAD

**Issue by jy-98** [Reedyuk/blue-falcon#105]
I directly opened the iOS project and reported an error， 
Showing Recent Issues
There is no XCFramework found at '/Users/xxxxx/library/build/XCFrameworks/release/BlueFalcon.xcframework'.
There is also no xcframework file in the project

**Comment by Reedyuk** [comment]
can you run 
```agsl
    cd library
    ./gradlew :assembleBlueFalconXCFramework 
```
it should generate the required framework

**Comment by Reedyuk** [comment]
All examples require you to build the project first, as we dont include the binary/framework in the sourcecode.
