### ISSUE TITLE
Kotlin MP Example

### ISSUE THREAD

**Issue by nicolasf** [Reedyuk/blue-falcon#106]
The Kotlin MP example apparently was deleted from the repository, but it's mentioned on the documentation.
Was this intentional?

**Comment by Reedyuk** [comment]
whoops, let me put it back

**Comment by Reedyuk** [comment]
Actually i don't think we ever had a KMM example. I need to do one for you.

**Comment by nicolasf** [comment]
Maybe it was deleted at this commit? https://github.com/Reedyuk/blue-falcon/commit/9bf7e4b80f497ac541a8e1605969209285f2a494

**Comment by Aleksandar98** [comment]
Hey @Reedyuk any news about KMM example?

**Comment by Reedyuk** [comment]
Sorry, have been busy recently.
It's pretty easy though, include package in common and then instantiate blue falcon in the common.

**Comment by Reedyuk** [comment]
Hi guys, i have added a very basic example now, a couple of notes:
1. Run on a real device - emulator/simulator wont work
2. When you press scan, it will output the results to the log
This should atleast point you in the right direction.
Let me know if this works for you guys

**Comment by Aleksandar98** [comment]
Thanks @Reedyuk , will be trying it out this week

**Comment by Reedyuk** [comment]
Great, good luck and enjoy. Let me know if anything needs changing. 
I will close this issue and you can raise an issue or discussion if you need anything
