### ISSUE TITLE
Adding to android project

### ISSUE THREAD

**Issue by KonnorTimmons1297** [Reedyuk/blue-falcon#11]
I'm not sure how to add this library to my project without cloning the repo and manually adding it. Has this project been setup on package repository yet?

**Comment by Reedyuk** [comment]
Hi Konnor, I am in the progress of adding the library to Bintray.
I will update this issue when it’s complete.
Thanks

**Comment by Reedyuk** [comment]
For a temp solution you can clone the repo and use it relatively like the android example.

**Comment by Reedyuk** [comment]
ive not had chance to test it yet:
https://search.maven.org/search?q=g:dev.bluefalcon

**Comment by Reedyuk** [comment]
Hi,
`implementation 'dev.bluefalcon:library-android:0.0.3'`
Try this, it should work now.
