### ISSUE TITLE
Allow log configuration

### ISSUE THREAD

**Issue by SarahDelCastillo** [Reedyuk/blue-falcon#113]
When scanning with BlueFalcon, the console is completely flooded with logs like this:

```Discovered device null
Discovered device null
Discovered device DatiPlus-K00001B
Discovered device DatiPlus-K00001B
Discovered device null
Discovered device null
Discovered device Apple TV
Discovered device Apple TV
Discovered device null
Discovered device null
Discovered device null
```

It would be great if we could configure/deactivate logging.

I tried just filtering on the console but its not a viable solution if I need to see other similar logs.

**Comment by Reedyuk** [comment]
Good point, we should probably expose some sort of logger interface and then allow the consumer of the library to set/handle the logs

**Comment by Reedyuk** [comment]
@SarahDelCastillo - this is now complete v 1.2.0
