### ISSUE TITLE
How to use communication by BluetoothSocket in common code?

### ISSUE THREAD

**Issue by explorerboom86** [Reedyuk/blue-falcon#114]
Hello! Could you help me understand can i use communication by BluetoothSocket in common code?

**Comment by Reedyuk** [comment]
What is blue socket? What exactly are you trying to do? On what platform?

**Comment by explorerboom86** [comment]
> Что такое синяя розетка? Что именно ты пытаешься сделать? На какой платформе?

I have an application that receives data via BluetoothSocket.inputStream on Android. I want to use KMM (Android, iOS) to work via Bluetooth. Can i use blue-falcon ?

**Comment by Reedyuk** [comment]
I believe blue socket is only for traditional Bluetooth connections, blue falcon only supports blue tooth low energy connections(BLE).

**Comment by explorerboom86** [comment]
Thank you!
