### ISSUE TITLE
Cannot create an xcframework for iOS

### ISSUE THREAD

**Issue by marcprux** [Reedyuk/blue-falcon#131]
The issue at https://github.com/Reedyuk/blue-falcon/issues/105 recommends using the `assembleBlueFalconXCFramework` to create an xcframework for use in iOS projects, but it appears to not be found:

```
zap blue-falcon/library % ./gradlew :assembleBlueFalconXCFramework 

> Configure project :
iosArm64
iosSimulatorArm64
iosX64
js
kotlinMultiplatform
macosArm64
macosX64
rpi
androidDebug
androidRelease

FAILURE: Build failed with an exception.

* What went wrong:
Cannot locate tasks that match ':assembleBlueFalconXCFramework' as task 'assembleBlueFalconXCFramework' not found in root project 'blue-falcon'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> For more on name expansion, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 525ms
```

I've tried a few other gradle targets like `assemble` and `iosX64Binaries`, but none of them seem to yield an `.xcframework` that I can include in an iOS project.

Is there some way to create this framework (ideally universal: iOS+iOSSimulator+macOS)?

**Comment by Reedyuk** [comment]
Hi @marcprux - thanks for reporting, i am going to remove all of the native examples, in favour of just using the KMP one instead.
Is there any need/use case for using a solely native example?
