### ISSUE TITLE
KMP CBCharacteristic only read value

### ISSUE THREAD

**Issue by TimurGaysin** [Reedyuk/blue-falcon#132]
In Swift version,  CBCharacteristic have read/write type. (https://developer.apple.com/documentation/corebluetooth/cbcharacteristic)https://developer.apple.com/documentation/corebluetooth/cbcharacteristic/value
In blue-falcon KMP version, CBCharacteristic  - have only read type(it defined as val) - CBCharacteristic.value cannot be reassigned.

**Comment by Reedyuk** [comment]
It is a computed property, Computed properties in Kotlin do not store a value directly but compute it on-the-fly using a getter. 

https://github.com/Reedyuk/blue-falcon/blob/2448f8f1ed17393ad88a536d50f14e404a6f59ff/library/src/appleMain/kotlin/dev/bluefalcon/BluetoothCharacteristic.kt#L15C5-L22C10

**Comment by Reedyuk** [comment]
can i ask, where are you getting "value cannot be reassigned"? are you saying this is ocurring during runtime?

**Comment by Reedyuk** [comment]
closing during inactivty
