### ISSUE TITLE
Update to Kotlin 1.3.50

### ISSUE THREAD

**Issue by Alex009** [Reedyuk/blue-falcon#14]
Please update library in maven repo to kotlin 1.3.50. Kotlin/Native require equals versions of libs with project's version

**Comment by Reedyuk** [comment]
Hey Alex, sure i will try to get this done asap.

**Comment by Reedyuk** [comment]
https://search.maven.org/search?q=dev.bluefalcon
Master is updated and just waiting for hosting to update. 0.0.4
