### ISSUE TITLE
API MISUSE

### ISSUE THREAD

**Issue by curiosities** [Reedyuk/blue-falcon#146]
**Describe the bug**

I can see below message After didDiscoverServices, 

API MISUSE : Discovering characteristic descriptors for peripheral <CBPeripheral: 0x303290680, identifier = state = connected> while delegate is either nil or does not implement peripheral:didDiscoverDescriptorsForCharacteristic:error:

**To Reproduce**
1. BLE Connect
2. See error

**Smartphone (please complete the following information):**
 - Device: iPhone16
 - OS: iOS18.0.1

**Additional context**

**Comment by Reedyuk** [comment]
Potentially could be introduced using ios 18. I assume they have changed the delegate.
