### ISSUE TITLE
Help with ios BluetoothUnknownException

### ISSUE THREAD

**Issue by felislynx-silae** [Reedyuk/blue-falcon#26]
First, thank you for upgrading library to latest Kotlin version.
Now i'm trying to use it with iphone.
I've empty project, added
Privacy - Bluetooth Always Usage Description
Privacy - Bluetooth Peripheral Usage Description
into Info.plist
and after running scan i've got
BluetoothUnknownException - Unknown error happened
Initialization of library is done like in sample: LibraryBlueFalcon(context: UIView(), serviceUUID: nil)
To be honest, i've no idea how to debug it or what is wrong with it :)

**Comment by Reedyuk** [comment]
Are you running this in the simulator? Any bluetooth services cannot be used on the simulator.

**Comment by felislynx-silae** [comment]
I've checked this on 5s and 11 (physical devices)

**Comment by Reedyuk** [comment]
Can you send me a zipped version of the project? I would also suggest you have a look at the example projects in this repo.

**Comment by felislynx-silae** [comment]
By the way, in my code its named LibraryBlueFalcon because kotlin made header file with prefixes to distinguish K/N libraries
