### ISSUE TITLE
Lack of TRANSPORT_LE for Android prevents from working with BLE UART connections

### ISSUE THREAD

**Issue by felislynx-silae** [Reedyuk/blue-falcon#27]
In Android when you use connectGatt you can pass TRANSPORT_LE as last parameter which might be required for some devices. Same thing can be done via changing characteristic descriptor parameter via gatt. Currently if i create gatt uart server on Raspberry Pi, i can connect to it and discover services/characteristics but read/writes are not working. This is not a case for iOS which works.

**Describe the solution you'd like**
Add parameter to enable TRANSPORT_LE or expose descriptor change for characteristic

**Additional context**
https://scribles.net/creating-ble-gatt-server-uart-service-on-raspberry-pi/ <-- sample code for raspberry pi 3
https://stackoverflow.com/questions/46273499/trouble-connecting-android-app-to-raspberry-pi-3-over-ble <-- some explanation

**Comment by Reedyuk** [comment]
I will try to have a look at this in the coming weeks, otherwise you are welcome to add your own PR with the changes.

**Comment by Reedyuk** [comment]
Hi @felislynx-silae, i am just working on the change now, you will be able to modify a property on the android BlueFalcon object called transport method, i will adjust the android example to accommodate for this.
![Screenshot 2020-04-01 at 12 51 36](https://user-images.githubusercontent.com/3853006/78134128-899c1980-7417-11ea-9332-7f29d6fab045.png)
