### ISSUE TITLE
Examples to show how to fetch services and characteristics

### ISSUE THREAD

**Issue by Reedyuk** [Reedyuk/blue-falcon#3]
Extend the current examples to show how to fetch bluetooth services and characteristics and then to fetch data from them.

**Comment by aohanhongzhi** [comment]
the service is always empty.

![Image](https://github.com/user-attachments/assets/cc3ff2ee-10dd-458c-9323-439ee3371239)


![Image](https://github.com/user-attachments/assets/771f4736-b87f-4c97-b219-c1645f410cc7)

Another BLE debug tool has discovered multiple services on this hardware device. 

![Image](https://github.com/user-attachments/assets/ecd4de54-3545-4a8a-9290-c629fd06dd60)


https://github.com/Reedyuk/blue-falcon/issues/156

**Comment by cloud-sunny** [comment]
I'd like to ask a question: how does the Xiaomi Mi Home app scan for and find its own devices via Bluetooth? I seem to be unable to obtain the `advertisementData`. Do you have any good ideas? Thanks for your reply.

**Comment by cloud-sunny** [comment]
<img width="2344" height="1716" alt="Image" src="https://github.com/user-attachments/assets/4f9f6161-234e-457d-896a-4b97bdbfeec9" />
scanRecord?.getServiceData()
How can I obtain this data?

**Comment by Reedyuk** [comment]
You can filter a scan for devices nearby, have a look at the scab function.
The scan filter will allow you to filter based on advertisement info

**Comment by cloud-sunny** [comment]
Information I got from android scanRecord?.getServiceData()

``` println("${name} ServiceData: ${scanRecord?.getServiceData().toString()}")
xiaomi.light.btlm2 ServiceData: {0000fe95-0000-1000-8000-00805f9b34fb=[-112, 84, -119, 84, 0, 55, -127, -103, 71, -82, 4, 14, 0]}
Mijia Scale S800 3C35 ServiceData: {0000fe95-0000-1000-8000-00805f9b34fb=[16, 89, -80, 108, 56, 53, 60, -13, -118, 67, -44]}

``` 
blueFalcon.scan(filters = listOf(ServiceFilter(Uuid.parse("0000fe95-0000-1000-8000-00805f9b34fb"))))
Now, filtering like this yields no results.

<img width="2344" height="1716" alt="Image" src="https://github.com/user-attachments/assets/9d7423cc-c58c-49ad-8bf9-e7addfceb791" />

> You can filter a scan for devices nearby, have a look at the scab function. The scan filter will allow you to filter based on advertisement info

**Comment by Reedyuk** [comment]
are you two related? https://github.com/Reedyuk/blue-falcon/issues/217
Seems odd to raise the same question in quick succession

**Comment by cloud-sunny** [comment]
> You can filter a scan for devices nearby, have a look at the scab function. The scan filter will allow you to filter based on advertisement info

Sorry, my description might have been incorrect. I appreciate your reply.

I tried scanning Bluetooth using the Android default method and got the `device.scanRecord` data, which contains the manufacturer data I need.

For example, `scanRecord.manufacturerSpecificData`/`scanRecord.manufacturerSpecificData.getServiceData()`. Because I can't determine the device I need to connect to based on the device name,

I didn't find a similar field in the SDK. How can I obtain this data? Has the SDK considered adding a new field?

**Comment by cloud-sunny** [comment]
> > You can filter a scan for devices nearby, have a look at the scab function. The scan filter will allow you to filter based on advertisement info
> 
> Sorry, my description might have been incorrect. I appreciate your reply.
> 
> I tried scanning Bluetooth using the Android default method and got the `device.scanRecord` data, which contains the manufacturer data I need.
> 
> For example, `scanRecord.manufacturerSpecificData`/`scanRecord.manufacturerSpecificData.getServiceData()`. Because I can't determine the device I need to connect to based on the device name,
> 
> I didn't find a similar field in the SDK. How can I obtain this data? Has the SDK considered adding a new field?

I tried running the scan function on the JVM platform with filters added, and it worked fine. However, it didn't find any results on the Android platform (API=36). I haven't tried it on iOS yet.

**Comment by Reedyuk** [comment]
Can you raise a separate issue, i will look into it for you
