### ISSUE TITLE
[ANDROID] OnConnected called when device is disconnected

### ISSUE THREAD

**Issue by felislynx-silae** [Reedyuk/blue-falcon#37]
This code listens to connection change event, it doesn't check what's new state, it always tries to "connect" to device and sends that information out. So if i'm connected and turn off external device, i get information that i'm connected :)
Didn't checked iOS (will do in upcoming weeks) yet.
```
override fun onConnectionStateChange(gatt: BluetoothGatt?, status: Int, newState: Int) {
            super.onConnectionStateChange(gatt, status, newState)
            log("onConnectionStateChange")
            gatt?.let { bluetoothGatt ->
                bluetoothGatt.device.let {
                    addGatt(bluetoothGatt)
                    bluetoothGatt.readRemoteRssi()
                    bluetoothGatt.discoverServices()
                    delegates.forEach {
                        it.didConnect(BluetoothPeripheral(bluetoothGatt.device))
                    }
                }
            }
        }
```

**Comment by Reedyuk** [comment]
good spot, we should check the status/new state to determine if connected.

**Comment by Reedyuk** [comment]
Hi @felislynx-silae - do you want to check my PR, this should address the issue you were experiencing.

**Comment by felislynx-silae** [comment]
Hi, it looks good. If more comes out during tests i'll  let you know :)
