### ISSUE TITLE
Library metadata is missing for kotlin MP

### ISSUE THREAD

**Issue by xPutnikx** [Reedyuk/blue-falcon#46]
Hi,
 
I'm trying to use the latest version of the library (0.7.0 and 0.7.1) and experience some problems with the dependencies in Kotlin multiplatform project.
I was able to reproduce the issue using the Kotlin-MP sample.

## The issue
When using the latest version of the library in the kotlin-multiplatform project, the dependencies in `commonMain` can't be resolved.

## Steps to reproduce
1. Open the Kotlin-MP sample from this repository.
2. Sync the project
3. Open commonMain -> DevicesViewModel.kt
4. Check that all dependencies resolved
5. Change BlueFalcon version from 0.6.6 to 0.7.1 (in gradle.properties)
6. Open commonMain -> DevicesViewModel.kt

### Expected behavior
Dependencies remain resolved

### Actual behavior
dev.bluefalcon can't be found.
<img width="507" alt="Screenshot 2020-07-27 at 17 40 56" src="https://user-images.githubusercontent.com/1839562/88562770-66821f00-d031-11ea-9add-784d98c25a20.png">

## Notes
I have done some research around the issue and compared dependencies for both versions (0.6.6 which works and 0.7.0-0.7.1 which doesn't)

In 0.6.6 version you have a package `library-metadata`
<img width="466" alt="Screenshot 2020-07-27 at 17 41 13" src="https://user-images.githubusercontent.com/1839562/88562873-874a7480-d031-11ea-89b1-1836b59fd408.png">
**0.6.6**

In 0.7.1 it disappered
<img width="472" alt="Screenshot 2020-07-27 at 17 40 35" src="https://user-images.githubusercontent.com/1839562/88562968-ab0dba80-d031-11ea-8262-abe71471477e.png">
**0.7.1**

I guess it might be some issue with packaging the library, but not sure. Would be glad to share any additional info needed to help to solve the issue.

**Comment by Reedyuk** [comment]
Yes, I must have broken it when i moved over to using Github actions. I will need to investigate why its not packaging correctly.
Thanks

**Comment by xPutnikx** [comment]
I have done a bit of investigation and tests just now. 
I see an issue on Kotlin tracker which might be related to that https://youtrack.jetbrains.com/issue/KT-34038

It looks like only AndroidStudio fails to resolve dependencies while the compiler actually works and compiles the project properly.

**Comment by Reedyuk** [comment]
What version of gradle are you using? im finding at the moment version 6+ has alot of issues.
I have reverted back to 5.6.4

**Comment by Reedyuk** [comment]
So checked to make sure maven central has all the libraries, it does:
![Screenshot 2020-08-01 at 21 27 20](https://user-images.githubusercontent.com/3853006/89109960-d29fc100-d43d-11ea-93fd-b992f3362198.png)

So im going to close this issue, as i think this is unfortunately a kotlin issue.
