### ISSUE TITLE
Add support for manufacturerSpecificData (Android) and kCBAdvDataManufacturerData (iOS)

### ISSUE THREAD

**Issue by etwilliams** [Reedyuk/blue-falcon#59]
I've been looking into the library for use in my companies BLE apps. It seems very simple to use and I look forward to being able to add this to our toolkit. One feature we use a lot is embedding information into the advertising data. Is it possible to add ScanRecord.manufacturerSpecificData (for Android) and kCBAdvDataManufacturerData (for iOS) into the BluetoothPeripheral class? I'm an Android developer and could help with that side.

**Comment by Reedyuk** [comment]
Nice idea, happy for you to put in a PR for this.

**Comment by bvitaliyg** [comment]
Was this API removed in 3.X? I see no way to retrieve these data anymore

**Comment by Reedyuk** [comment]
> Was this API removed in 3X? I see no way to retrieve these data anymore

https://github.com/Reedyuk/blue-falcon/pull/230

**Comment by Reedyuk** [comment]
@bvitaliyg version 3.5.0 should be published in 10 minutes

**Comment by bvitaliyg** [comment]
Wow, that was blazingly fast. Thank you a lot!
