### ISSUE TITLE
Add support for new Kotlin IR

### ISSUE THREAD

**Issue by ln-12** [Reedyuk/blue-falcon#60]
The library is currently not compatible with [the new Kotlin IR ](https://kotlinlang.org/docs/reference/whatsnew14.html#new-jvm-ir-backend). I setup a minimal example [here](https://github.com/ln-12/kmm_ir_issue). Please add support for this new backend.

**Comment by Reedyuk** [comment]
Hi, what sort of impact would this have on people using none kotlin IR projects? I would'nt want to restrict people using this library already.

**Comment by ln-12** [comment]
I really don't know. That seems to be a big problem as you can't mix libraries that support and don't support IR. Maybe two artifacts would be appropriate?

**Comment by Reedyuk** [comment]
Its currently in alpha, is there a reason for the push to support it right now?

**Comment by ln-12** [comment]
You must enable IR if you want to use Jetpack compose.

**Comment by Reedyuk** [comment]
I have added a PR to enable IR but i haven't had chance to update android example.

**Comment by ln-12** [comment]
Great! Thanks for your fast reply 😄

**Comment by ln-12** [comment]
I can conform that it works after updating to Kotlin 1.4.30.
