### ISSUE TITLE
BlueFalcon not found in iOS

### ISSUE THREAD

**Issue by AsifArhan** [Reedyuk/blue-falcon#86]
I am getting below error while running the iOS example project
There is no XCFramework found at '/Users/apple/Downloads/blue-falcon-master/library/build/universal/BlueFalcon.xcframework'.

**Comment by Reedyuk** [comment]
run the gradle task makeUniversalFramework
Then try again.

**Comment by AsifArhan** [comment]
I don't have kotlin installed in my mac, do i need to download kotlin for this?

**Comment by Reedyuk** [comment]
this library probably isn't for you then. It is to be used for kotlin multiplatform projects, the intention was not to be used independently on ios(technically if you had the universal framework you could make it work but probably not worth it).

**Comment by AsifArhan** [comment]
Thank you for the quick response, is there any way to do it in iOS if you could suggest

**Comment by Reedyuk** [comment]
Depends on what 'it' is, if you mean interact with bluetooth in ios? then there is plenty of great tutorials online using the sdk's provided by apple.

**Comment by AsifArhan** [comment]
Okay Thank you

**Comment by ZuhanLin** [comment]
> 

can not find makeUniversalFramework，pls tell me detail steps，ths

**Comment by Reedyuk** [comment]
You need to run the task assemblexcframework
I need to update the readme

**Comment by ZuhanLin** [comment]
> 

Thank you，i got it

**Comment by ZuhanLin** [comment]
![image](https://user-images.githubusercontent.com/5183529/163569125-5cc99551-955f-41b4-a7de-435ac075ad6d.png)
ios-arm64-simulator is needless，how to remove it？

**Comment by Reedyuk** [comment]
You need to check the build gradle script and you can set the iOS target that is desired.
It's strange it didn't generate all the iOS targets. It's not much of a universal framework when it's only one target architecture

**Comment by ZuhanLin** [comment]
> You need to check the build gradle script and you can set the iOS target that is desired. It's strange it didn't generate all the iOS targets. It's not much of a universal framework when it's only one target architecture

Thank you for your response，I had run successfully in my device
