### ISSUE TITLE
The project 'blue-falcon' is not a Gradle-based project

### ISSUE THREAD

**Issue by ZuhanLin** [Reedyuk/blue-falcon#93]
Project Sync
The project 'blue-falcon' is not a Gradle-based project

**Comment by Reedyuk** [comment]
@ZuhanLin - Any more details? the CI is building the project so i doubt its a problem on the project. Maybe an issue with your current setup?

**Comment by ZuhanLin** [comment]
> @ZuhanLin - Any more details? the CI is building the project so i doubt its a problem on the project. Maybe an issue with your current setup?

i clone the project, and Sync project with gradle files by Android Studio ,

**Comment by ZuhanLin** [comment]
![image](https://user-images.githubusercontent.com/5183529/166894821-d4d8c32a-ea84-4fb9-bbca-8b6f664ab561.png)

**Comment by Reedyuk** [comment]
I have just tried it with latest master and its working. 
Can you try intellij? Make sure you have the latest version, as its using Kotlin 1.6.21

**Comment by ZuhanLin** [comment]
> I have just tried it with latest master and its working. Can you try intellij? Make sure you have the latest version, as its using Kotlin 1.6.21

I download the latest Intellij, but got error that 'This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.1.1 or newer.
'

**Comment by Reedyuk** [comment]
Run the build task, does it succeed. 
I get that error too on gradle sync, but usually the gradle build task will still succeed.

**Comment by Reedyuk** [comment]
![Screenshot 2022-05-05 at 11 39 07](https://user-images.githubusercontent.com/3853006/166907358-be4fc01f-b441-437c-a5ab-f0602eddaca2.png)

**Comment by ZuhanLin** [comment]
> Run the build task, does it succeed? I get that error too on gradle sync, but usually the gradle build task will still succeed.

i can not find the gradle task list

**Comment by Reedyuk** [comment]
and if you run 
```
./gradlew build
```
does it work?

**Comment by ZuhanLin** [comment]
> and if you run
> 
> ```
> ./gradlew build
> ```
> 
> does it work?

Yerp, it is SUCCESS ，how can i execute special task

**Comment by Reedyuk** [comment]
Special task? sounds awesome, i have no idea what you mean by special task.

maybe the question to be asked is, What exactly are you trying to do?

**Comment by ZuhanLin** [comment]
i can not find gradle task list，sorry ，i am a beginner of gradle project and Intellij

**Comment by Reedyuk** [comment]
When opening the root folder of the project, i would strongly recommend you open it with Intellij.
When opening the android examples, you should use android studio.

I find this works best for this project - maybe some bugs Jetbrains have not fixed.

If you open the project in intellij and press the reload button.

![Screenshot 2022-05-06 at 09 03 34](https://user-images.githubusercontent.com/3853006/167092154-a44fb0df-d663-4072-ade0-9c618418cd35.png)

Then it should produce the list of tasks.

**Comment by ZuhanLin** [comment]
> When opening the root folder of the project, i would strongly recommend you open it with Intellij. When opening the android examples, you should use android studio.
> 
> I find this works best for this project - maybe some bugs Jetbrains have not fixed.
> 
> If you open the project in intellij and press the reload button.
> 
> ![Screenshot 2022-05-06 at 09 03 34](https://user-images.githubusercontent.com/3853006/167092154-a44fb0df-d663-4072-ade0-9c618418cd35.png)
> 
> Then it should produce the list of tasks.

it is not list gradle task but errors below image
![image](https://user-images.githubusercontent.com/5183529/167093721-7341fb21-b0ce-4b44-85f0-c916d0313325.png)

**Comment by Reedyuk** [comment]
it could be related to the gradle wrapper you are using.
I would recommend you delete the current one and reload it to fetch a new one.

The android support plugin is very twitchy.

**Comment by ZuhanLin** [comment]
How to debug with xcode or Android studio，is there any Tutorials

**Comment by Reedyuk** [comment]
https://kotlinlang.org/docs/multiplatform-mobile-create-first-app.html
